### ISSUE TITLE
Cannot connect to LS50W2

### ISSUE THREAD

**Issue by aliparr-** [N0ciple/hass-kef-connector#3]
Upon HomeAssistant startup I get this error logged:

```
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.170:80 ssl:default [Connect call failed ('192.168.1.170', 80)]
```

192.168.1.170 is the IP address of my LS50W2s - which are on/working etc.

My configuration.yaml looks like this:

```
media_player:
  - platform: kef_connector
    host: 192.168.1.170
    name: "Butterfly Kef Speakers"
    maximum_volume: 1.0
    volume_step: 0.03
```
    
Also, question... if this does work, how does the device show up? This wasn't clear from the readme. It shows up as a device with entities? I see nothing in my device list.

Many thanks!
