### ISSUE TITLE
Via an automation, LSX II cannot Stop or Play Media

### ISSUE THREAD

**Issue by gurmukhp** [N0ciple/hass-kef-connector#5]
Hello

Thanks for making this plugin, I have managed to install it and create a dashboard card that can control the Kef Speaker (play / pause etc).

However when I try to do this via an automation, I get the following error:

`Entity media_player.kef_speaker does not support this service.`

This is a super simple YAML file I'm using:

```
alias: Stop Kef
description: ""
trigger: []
condition: []
action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.kef_speaker
mode: single
```

I also am not able to play music via an automation.

If it helps, mute, unmute, volume up, volume down, volume set, pause, play all seem to work, it's just 'stop' and 'play media'. A workaround is to use 'Media Player: turn off' which works! ⭐️

I'm happy to beta test anything you might create.

Thanks!
